group = Group.create(code: 1234, name: "Test Group")
AgeGroup.create(description: "Adult (12+)")
AgeGroup.create(description: "Child Under 12")
AgeGroup.create(description: "Child Under 5")
event1 = Event.create(title: "Manglik Prasango")
event2 = Event.create(title: "Raas-Garba")
event3 = Event.create(title: "Wedding")
event4 = Event.create(title: "Reception")
event1.invites.create(group_id: group.id, num_invited: 1)
event2.invites.create(group_id: group.id, num_invited: 2)
event3.invites.create(group_id: group.id, num_invited: 3)
event4.invites.create(group_id: group.id, num_invited: 4)
